### ISSUE TITLE
To specify fields to be skipped per Type or Resolver

### ISSUE THREAD

**Issue by isaka1022** [bitjourney/graphql-autotest#13]
The way it's made now, skipping can only be specified by field name,  as shown blow.

```ruby
# Skip a sensitive field
skip_if = proc do |field|
  field.name == 'sensitiveField'
end
```

However, this would cause both to be skipped if other models have fields with the same name, as shown below.

```ruby
class HogeType < BaseObject
  field :id, ID, null: true
end

class FugaType < BaseObject
  field :id, ID, null: true
end

```
Specifying the following will skip the id field for both types.

```
field.name == 'id'
```

Is it possible to specify fields to be skipped per Type or Resolver?

**Comment by moeki0** [comment]
Hi @isaka1022. I think we can specify type like:

```ruby
util = GraphQL::Autotest::Util

skip_if = -> (field, ancestors:) do
  field.name == 'id' && ancestors.first && util.unwrap(ancestors.first.type).name == 'Hoge')
end
```

ref: https://github.com/bitjourney/graphql-autotest/blob/919f599468c3fb706433dd4007b899321c617a2b/lib/graphql/autotest/query_generator.rb#L38

The documentation is insufficient. Sorry.

**Comment by isaka1022** [comment]
Sorry for late reply.
Thank you for your cooperation and I will try.
